### ISSUE TITLE
integrate go releaser 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos-update-worker#3]

**Comment by mohamedamer453** [comment]
Verified.

A goreleaser workflow was added in #6.
However there're no runs yet for this workflow to verify that it's working from.

![image](https://user-images.githubusercontent.com/101194226/206478063-e09a3b12-c273-4579-97ad-ae131ad91631.png)

Will reopen this issue if there's a problem with the workflow in future runs.
