### ISSUE TITLE
release 1.0.0-rc1

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos-update-worker#4]

**Comment by mohamedamer453** [comment]
Verified.

Followed the steps in the read me and i was able to run the binary of the latest [release](https://github.com/threefoldtech/zos-update-worker/releases/tag/v1.0.0-rc1).

![image](https://user-images.githubusercontent.com/101194226/206476437-d1a5391d-e186-4ed8-8232-f4d06369fd70.png)

and it ran successfully without any errors.

![image](https://user-images.githubusercontent.com/101194226/206476564-4419e668-d407-40bd-a85f-39e7f9a24b07.png)
